# Generated by Django 6.1 on 2026-08-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='download_token',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
